"""Add DatosCliente table

Revision ID: 134e90d2d22e
Revises: fb720bfe1717
Create Date: 2026-04-26 23:36:57.035161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134e90d2d22e'
down_revision: Union[str, None] = 'fb720bfe1717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datos_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('documento', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('atencion', sa.String(length=255), nullable=True),
    sa.Column('referencia', sa.Text(), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datos_cliente_id'), 'datos_cliente', ['id'], unique=False)
    op.create_index(op.f('ix_datos_cliente_nombre'), 'datos_cliente', ['nombre'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datos_cliente_nombre'), table_name='datos_cliente')
    op.drop_index(op.f('ix_datos_cliente_id'), table_name='datos_cliente')
    op.drop_table('datos_cliente')
    # ### end Alembic commands ###
