"""Add plantillas_globales table

Revision ID: 2f82d74bdf82
Revises: 134e90d2d22e
Create Date: 2026-04-27 13:40:33.998399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f82d74bdf82'
down_revision: Union[str, None] = '134e90d2d22e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plantillas_globales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cond_tecnicas', sa.JSON(), nullable=True),
    sa.Column('cond_comerciales', sa.JSON(), nullable=True),
    sa.Column('cond_otras', sa.JSON(), nullable=True),
    sa.Column('cond_garantia', sa.JSON(), nullable=True),
    sa.Column('cond_garantia_servicio', sa.Text(), nullable=True),
    sa.Column('cuentas_bancarias', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plantillas_globales')
    # ### end Alembic commands ###
