"""Add mostrar_cond flags to cotizaciones

Revision ID: 8001952056d7
Revises: 2f82d74bdf82
Create Date: 2026-04-27 15:02:09.227878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8001952056d7'
down_revision: Union[str, None] = '2f82d74bdf82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    default_true = sa.text('true')
    op.add_column('cotizaciones', sa.Column('mostrar_cond_tecnicas', sa.Boolean(), nullable=False, server_default=default_true))
    op.add_column('cotizaciones', sa.Column('mostrar_cond_comerciales', sa.Boolean(), nullable=False, server_default=default_true))
    op.add_column('cotizaciones', sa.Column('mostrar_cond_otras', sa.Boolean(), nullable=False, server_default=default_true))
    op.add_column('cotizaciones', sa.Column('mostrar_cond_garantia', sa.Boolean(), nullable=False, server_default=default_true))
    op.add_column('cotizaciones', sa.Column('mostrar_cond_garantia_servicio', sa.Boolean(), nullable=False, server_default=default_true))
    op.add_column('cotizaciones', sa.Column('mostrar_cuentas_bancarias', sa.Boolean(), nullable=False, server_default=default_true))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cotizaciones', 'mostrar_cuentas_bancarias')
    op.drop_column('cotizaciones', 'mostrar_cond_garantia_servicio')
    op.drop_column('cotizaciones', 'mostrar_cond_garantia')
    op.drop_column('cotizaciones', 'mostrar_cond_otras')
    op.drop_column('cotizaciones', 'mostrar_cond_comerciales')
    op.drop_column('cotizaciones', 'mostrar_cond_tecnicas')
    # ### end Alembic commands ###
