"""add_visitas_table

Revision ID: b54495892914
Revises: 8001952056d7
Create Date: 2026-05-20 23:10:05.590556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b54495892914'
down_revision: Union[str, None] = '8001952056d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_cliente', sa.String(length=50), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('lng', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('tipo_sistema', sa.String(length=100), nullable=False),
    sa.Column('conexion_red', sa.String(length=20), nullable=True),
    sa.Column('cargas_aislado', sa.JSON(), nullable=False),
    sa.Column('tipo_techo', sa.String(length=100), nullable=True),
    sa.Column('obs_techo', sa.Text(), nullable=True),
    sa.Column('obs_interior', sa.Text(), nullable=True),
    sa.Column('recibo_ruta', sa.String(length=500), nullable=True),
    sa.Column('fotos_techo', sa.JSON(), nullable=False),
    sa.Column('fotos_interior', sa.JSON(), nullable=False),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['datos_cliente.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tecnico_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitas_cliente_id'), 'visitas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_visitas_fecha'), 'visitas', ['fecha'], unique=False)
    op.create_index(op.f('ix_visitas_id'), 'visitas', ['id'], unique=False)
    op.create_index(op.f('ix_visitas_tecnico_id'), 'visitas', ['tecnico_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitas_tecnico_id'), table_name='visitas')
    op.drop_index(op.f('ix_visitas_id'), table_name='visitas')
    op.drop_index(op.f('ix_visitas_fecha'), table_name='visitas')
    op.drop_index(op.f('ix_visitas_cliente_id'), table_name='visitas')
    op.drop_table('visitas')
    # ### end Alembic commands ###
