"""add paso_actual to visitas

Revision ID: fa42aec2415c
Revises: b54495892914
Create Date: 2026-05-22 01:24:30.704675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa42aec2415c'
down_revision: Union[str, None] = 'b54495892914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitas', sa.Column('paso_actual', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visitas', 'paso_actual')
    # ### end Alembic commands ###
