"""add planner tables

Revision ID: fb59ae7fba2b
Revises: f2a3b4c5d6e7
Create Date: 2026-06-21 16:17:36.845188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb59ae7fba2b'
down_revision: Union[str, None] = 'f2a3b4c5d6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planner_feriados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('nacional', 'regional', name='tipoferiado'), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('recurrente', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planner_personal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('profesion', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'inactivo', name='estadomiembro'), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planner_proyectos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('cliente', sa.String(length=200), nullable=True),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('paneles', sa.Integer(), nullable=True),
    sa.Column('avance_planificado', sa.Float(), nullable=True),
    sa.Column('avance_real', sa.Float(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'en_progreso', 'completado', 'cancelado', name='estadoproyecto'), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('fecha_fin_real', sa.Date(), nullable=True),
    sa.Column('alcance', sa.Text(), nullable=True),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('inspector_visita_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planner_cuadrillas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['planner_proyectos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planner_curva_s_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('avance_planificado', sa.Float(), nullable=True),
    sa.Column('avance_real', sa.Float(), nullable=True),
    sa.Column('actividades_total', sa.Integer(), nullable=True),
    sa.Column('actividades_hechas', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['planner_proyectos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planner_actividades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('padre_id', sa.Integer(), nullable=True),
    sa.Column('cuadrilla_id', sa.Integer(), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio_plan', sa.Date(), nullable=True),
    sa.Column('fecha_fin_plan', sa.Date(), nullable=True),
    sa.Column('duracion_dias', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio_real', sa.Date(), nullable=True),
    sa.Column('fecha_fin_real', sa.Date(), nullable=True),
    sa.Column('avance', sa.Float(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'en_curso', 'completado', 'bloqueado', name='estadoactividad'), nullable=False),
    sa.Column('prioridad', sa.Enum('alta', 'media', 'baja', name='prioridadactividad'), nullable=False),
    sa.Column('subtareas', sa.JSON(), nullable=True),
    sa.Column('es_hito', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cuadrilla_id'], ['planner_cuadrillas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['padre_id'], ['planner_actividades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proyecto_id'], ['planner_proyectos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsable_id'], ['planner_personal.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planner_asistencia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=True),
    sa.Column('cuadrilla_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('presente', 'tardanza', 'ausente', name='estadoasistencia'), nullable=False),
    sa.Column('hora', sa.String(length=10), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('observacion', sa.String(length=300), nullable=True),
    sa.Column('registrado_por', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cuadrilla_id'], ['planner_cuadrillas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['persona_id'], ['planner_personal.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proyecto_id'], ['planner_proyectos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planner_miembros_cuadrilla',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cuadrilla_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('rol_interno', sa.Enum('jefe_cuadrilla', 'capataz', 'tecnico', 'instalador', 'operario', 'peon', 'supervisor', 'ingeniero', 'otro', name='rolcuadrilla'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('fecha_salida', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cuadrilla_id'], ['planner_cuadrillas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persona_id'], ['planner_personal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planner_dependencias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actividad_id', sa.Integer(), nullable=False),
    sa.Column('depende_de_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('fs', 'ss', 'ff', 'sf', name='tipodependencia'), nullable=False),
    sa.Column('lag_dias', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['planner_actividades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['depende_de_id'], ['planner_actividades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planner_fotos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('actividad_id', sa.Integer(), nullable=True),
    sa.Column('etapa', sa.String(length=200), nullable=True),
    sa.Column('etapa_codigo', sa.String(length=50), nullable=True),
    sa.Column('subido_por', sa.String(length=200), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('ruta', sa.String(length=500), nullable=True),
    sa.Column('nombre_original', sa.String(length=300), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('incluir_en_pdf', sa.Boolean(), nullable=True),
    sa.Column('comentario_pdf', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['planner_actividades.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proyecto_id'], ['planner_proyectos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planner_fotos')
    op.drop_table('planner_dependencias')
    op.drop_table('planner_miembros_cuadrilla')
    op.drop_table('planner_asistencia')
    op.drop_table('planner_actividades')
    op.drop_table('planner_curva_s_snapshots')
    op.drop_table('planner_cuadrillas')
    op.drop_table('planner_proyectos')
    op.drop_table('planner_personal')
    op.drop_table('planner_feriados')
    # Eliminar los tipos enum nativos de PostgreSQL (drop_table no los borra) para
    # que un upgrade posterior pueda recrearlos sin "type already exists".
    for _enum in (
        'tipoferiado', 'estadomiembro', 'estadoproyecto', 'estadoactividad',
        'prioridadactividad', 'estadoasistencia', 'rolcuadrilla', 'tipodependencia',
    ):
        op.execute(f'DROP TYPE IF EXISTS {_enum}')
    # ### end Alembic commands ###
