"""Add rol to usuarios

Revision ID: fb720bfe1717
Revises: 001
Create Date: 2026-04-26 23:11:40.738795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb720bfe1717'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cotizaciones_correlativo_key', 'cotizaciones', type_='unique')
    op.drop_index('idx_cotizaciones_correlativo', table_name='cotizaciones')
    op.drop_index('idx_cotizaciones_estado', table_name='cotizaciones')
    op.create_index(op.f('ix_cotizaciones_correlativo'), 'cotizaciones', ['correlativo'], unique=True)
    op.create_index(op.f('ix_cotizaciones_id'), 'cotizaciones', ['id'], unique=False)
    op.drop_index('idx_items_cotizacion_id', table_name='items_cotizacion')
    op.create_index(op.f('ix_items_cotizacion_cotizacion_id'), 'items_cotizacion', ['cotizacion_id'], unique=False)
    op.create_index(op.f('ix_items_cotizacion_id'), 'items_cotizacion', ['id'], unique=False)
    op.drop_index('idx_productos_categoria', table_name='productos')
    op.drop_index('idx_productos_nombre', table_name='productos')
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.create_index(op.f('ix_productos_nombre'), 'productos', ['nombre'], unique=False)
    op.add_column('usuarios', sa.Column('rol', sa.String(length=50), server_default='vendedor', nullable=False))
    op.drop_index('idx_usuarios_correo', table_name='usuarios')
    op.drop_constraint('usuarios_correo_key', 'usuarios', type_='unique')
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios')
    op.create_unique_constraint('usuarios_correo_key', 'usuarios', ['correo'])
    op.create_index('idx_usuarios_correo', 'usuarios', ['correo'], unique=False)
    op.drop_column('usuarios', 'rol')
    op.drop_index(op.f('ix_productos_nombre'), table_name='productos')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.create_index('idx_productos_nombre', 'productos', ['nombre'], unique=False)
    op.create_index('idx_productos_categoria', 'productos', ['categoria'], unique=False)
    op.drop_index(op.f('ix_items_cotizacion_id'), table_name='items_cotizacion')
    op.drop_index(op.f('ix_items_cotizacion_cotizacion_id'), table_name='items_cotizacion')
    op.create_index('idx_items_cotizacion_id', 'items_cotizacion', ['cotizacion_id'], unique=False)
    op.drop_index(op.f('ix_cotizaciones_id'), table_name='cotizaciones')
    op.drop_index(op.f('ix_cotizaciones_correlativo'), table_name='cotizaciones')
    op.create_index('idx_cotizaciones_estado', 'cotizaciones', ['estado'], unique=False)
    op.create_index('idx_cotizaciones_correlativo', 'cotizaciones', ['correlativo'], unique=False)
    op.create_unique_constraint('cotizaciones_correlativo_key', 'cotizaciones', ['correlativo'])
    # ### end Alembic commands ###
